[[profiles]]
name = "Personal"
synced_files = [
    ".exportsrc",
    ".gitconfig",
    ".p10k.zsh",
    ".profile",
    ".sshconfig",
    ".tmux.conf",
    ".vimrc",
    ".zshenv",
    ".zshrc",
]

[[profiles.packages]]
name = "eza"
description = "ls replacement"
manager = "brew"
package_name = "eza"
binary_name = "eza"

[[profiles.packages]]
name = "httpie"
description = "curl replacement"
manager = "brew"
package_name = "httpie"
binary_name = "httpie"

[[profiles.packages]]
name = "trash"
description = "Trash helper"
manager = "brew"
package_name = "trash"
binary_name = "trash"

[[profiles.packages]]
name = "rename"
description = "batch rename tool"
manager = "brew"
package_name = "rename"
binary_name = "rename"

[[profiles.packages]]
name = "tig"
description = "tig git manager"
manager = "brew"
package_name = "tig"
binary_name = "tig"

[[profiles]]
name = "Linux"
description = "my linux machine setup"
synced_files = [
    ".gitconfig",
    ".p10k.zsh",
    ".profile",
    ".sshconfig",
    ".tmux.conf",
    ".vimrc",
    ".zshenv",
    ".zshrc",
]
packages = []
