[common]
synced_files = [
    ".config/atuin/config.toml",
    ".config/nvim",
    ".gitconfig",
    ".tmux.conf",
    ".vimrc",
    ".yarnrc",
    "scripts",
]

[[profiles]]
name = "Personal"
synced_files = [
    ".chirp/chirp.config",
    ".exportsrc",
    ".p10k.zsh",
    ".profile",
    ".seko-test",
    ".ssh/known_hosts",
    ".sshconfig",
    ".zshrc",
]

[[profiles.packages]]
name = "eza"
description = "ls replacement"
manager = "brew"
package_name = "eza"
binary_name = "eza"

[[profiles.packages]]
name = "httpie"
description = "curl replacement"
manager = "brew"
package_name = "httpie"
binary_name = "httpie"

[[profiles.packages]]
name = "Trash"
description = "Trash helper"
manager = "brew"
package_name = "trash"
binary_name = "trash"

[[profiles.packages]]
name = "Rename"
description = "a batch rename tool"
manager = "brew"
package_name = "rename"
binary_name = "rename"

[[profiles.packages]]
name = "Tig"
description = "Tig git cli"
manager = "brew"
package_name = "tig"
binary_name = "tig"

[[profiles.packages]]
name = "Midnight Commander"
description = "Terminal file browser"
manager = "brew"
package_name = "mc"
binary_name = "mc"

[[profiles.packages]]
name = "Bat"
description = "Bat is a nice Cat replacement"
manager = "brew"
package_name = "bat"
binary_name = "bat"

[[profiles.packages]]
name = "Antigen"
description = "Plugin manager for zsh, inspired by oh-my-zsh and vundle"
manager = "brew"
package_name = "antigen"
binary_name = "antigen"

[[profiles.packages]]
name = "Github CLI"
description = "Github cli tools"
manager = "brew"
package_name = "gh"
binary_name = "gh"

[[profiles.packages]]
name = "NeoVim"
description = "Better vim"
manager = "brew"
package_name = "neovim"
binary_name = "neovim"

[[profiles.packages]]
name = "FZF"
description = "Command-line fuzzy finder"
manager = "brew"
package_name = "fzf"
binary_name = "fzf"

[[profiles.packages]]
name = "FD"
description = "Better find"
manager = "brew"
package_name = "fd"
binary_name = "fd"

[[profiles.packages]]
name = "jq"
description = "Json Query tool"
manager = "brew"
package_name = "jq"
binary_name = "jq"

[[profiles.packages]]
name = "tmux"
description = "remote terminal helper"
manager = "brew"
package_name = "tmux"
binary_name = "tmux"

[[profiles.packages]]
name = "htop"
description = "Better system resource monitoring"
manager = "brew"
package_name = "htop"
binary_name = "htop"

[[profiles.packages]]
name = "atuin"
description = "Improved shell history for zsh, bash, fish and nushell"
manager = "brew"
package_name = "atuin"
binary_name = "atuin"

[[profiles.packages]]
name = "micro"
description = "more than nano, less then vim"
manager = "brew"
package_name = "micro"
binary_name = "micro"

[[profiles.packages]]
name = "ATAC"
description = "A simple API client (postman like) in your terminal"
manager = "brew"
package_name = "atac"
binary_name = "atac"

[[profiles.packages]]
name = "cargo-machete"
manager = "cargo"
package_name = "cargo-machete"
binary_name = "cargo-machete"

[[profiles.packages]]
name = "asciinema"
manager = "brew"
package_name = "asciinema"
binary_name = "asciinema"

[[profiles.packages]]
name = "lazygit"
manager = "brew"
package_name = "lazygit"
binary_name = "lazygit"

[[profiles.packages]]
name = "@google/gemini-cli"
manager = "npm"
package_name = "@google/gemini-cli"
binary_name = "@google/gemini-cli"

[[profiles.packages]]
name = "nvm"
manager = "brew"
package_name = "nvm"
binary_name = "nvm"

[[profiles.packages]]
name = "vercel"
manager = "npm"
package_name = "vercel"
binary_name = "vercel"

[[profiles.packages]]
name = "ripgrep"
description = "ripgrep recursively searches directories for a regex pattern while respecting your gitignore"
manager = "brew"
package_name = "ripgrep"
binary_name = "rg"

[[profiles.packages]]
name = "luarocks"
manager = "brew"
package_name = "luarocks"
binary_name = "luarocks"

[[profiles.packages]]
name = "wget"
manager = "brew"
package_name = "wget"
binary_name = "wget"

[[profiles.packages]]
name = "ast-grep"
manager = "brew"
package_name = "ast-grep"
binary_name = "ast-grep"

[[profiles]]
name = "Linux"
description = "my linux machine setup"
synced_files = [
    ".p10k.zsh",
    ".profile",
    ".sshconfig",
    ".zshenv",
    ".zshrc",
]
packages = []

[[profiles]]
name = "Exedev"
description = "exe.dev profile for ubuntu"
synced_files = [
    ".bash-preexec.sh",
    ".bash_logout",
    ".bashrc",
    ".profile",
    ".ssh/known_hosts",
]

[[profiles.packages]]
name = "Atuin"
description = "Magical Shell History"
manager = "custom"
binary_name = "atuin"
install_command = "curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh"
existence_check = "which atuin"

[[profiles.packages]]
name = "Eza"
description = "Eza for ls"
manager = "apt"
package_name = "eza"
binary_name = "eza"

[[profiles.packages]]
name = "bat"
manager = "apt"
package_name = "bat"
binary_name = "batcat"

[[profiles.packages]]
name = "HTTPIE"
description = "curl alternative"
manager = "apt"
package_name = "httpie"
binary_name = "httpie"

[[profiles.packages]]
name = "Docker Compose"
description = "Docker Compose"
manager = "apt"
package_name = "docker-compose"
binary_name = "docker-compose"

[[profiles.packages]]
name = "jq"
manager = "apt"
package_name = "jq"
binary_name = "jq"

[[profiles.packages]]
name = "gh"
manager = "apt"
package_name = "gh"
binary_name = "gh"

[[profiles.packages]]
name = "htop"
manager = "apt"
package_name = "htop"
binary_name = "htop"

[[profiles.packages]]
name = "cowsay"
manager = "apt"
package_name = "cowsay"
binary_name = "cowsay"

[[profiles.packages]]
name = "neovim repo"
description = "this is the ppa for latest version of neovim"
manager = "custom"
binary_name = "none"
install_command = "~/scripts/exedev-neovim.sh"
existence_check = "ls ~/.install-done"

[[profiles]]
name = "test"
description = "this is a development test profile"
synced_files = [
    ".chirp/chirp.config",
    ".exportsrc",
    ".p10k.zsh",
    ".profile",
    ".seko-test",
    ".sshconfig",
    ".test-folder",
    ".zshrc",
]
packages = []
