[[profiles]]
name = "Personal"
synced_files = [
    ".chirp/chirp.config",
    ".config/atuin/config.toml",
    ".exportsrc",
    ".gitconfig",
    ".p10k.zsh",
    ".profile",
    ".sshconfig",
    ".test-folder/aa.txt",
    ".tmux.conf",
    ".vimrc",
    ".zshenv",
    ".zshrc",
    "scripts",
]

[[profiles.packages]]
name = "eza"
description = "ls replacement"
manager = "brew"
package_name = "eza"
binary_name = "eza"

[[profiles.packages]]
name = "httpie"
description = "curl replacement"
manager = "brew"
package_name = "httpie"
binary_name = "httpie"

[[profiles.packages]]
name = "Trash"
description = "Trash helper"
manager = "brew"
package_name = "trash"
binary_name = "trash"

[[profiles.packages]]
name = "Rename"
description = "a batch rename tool"
manager = "brew"
package_name = "rename"
binary_name = "rename"

[[profiles.packages]]
name = "Tig"
description = "Tig git cli"
manager = "brew"
package_name = "tig"
binary_name = "tig"

[[profiles.packages]]
name = "Midnight Commander"
description = "Terminal file browser"
manager = "brew"
package_name = "mc"
binary_name = "mc"

[[profiles.packages]]
name = "Bat"
description = "Bat is a nice Cat replacement"
manager = "brew"
package_name = "bat"
binary_name = "bat"

[[profiles.packages]]
name = "Antigen"
description = "Plugin manager for zsh, inspired by oh-my-zsh and vundle"
manager = "brew"
package_name = "antigen"
binary_name = "antigen"

[[profiles.packages]]
name = "Github CLI"
description = "Github cli tools"
manager = "brew"
package_name = "gh"
binary_name = "gh"

[[profiles.packages]]
name = "NeoVim"
description = "Better wim"
manager = "brew"
package_name = "nvim"
binary_name = "nvim"

[[profiles.packages]]
name = "FZF"
description = "Command-line fuzzy finder"
manager = "brew"
package_name = "fzf"
binary_name = "fzf"

[[profiles.packages]]
name = "FD"
description = "Better find"
manager = "brew"
package_name = "fd"
binary_name = "fd"

[[profiles.packages]]
name = "jq"
description = "Json Query tool"
manager = "brew"
package_name = "jq"
binary_name = "jq"

[[profiles.packages]]
name = "tmux"
description = "remote terminal helper"
manager = "brew"
package_name = "tmux"
binary_name = "tmux"

[[profiles.packages]]
name = "htop"
description = "Better system resource monitoring"
manager = "brew"
package_name = "htop"
binary_name = "htop"

[[profiles.packages]]
name = "atuin"
description = "Improved shell history for zsh, bash, fish and nushell"
manager = "brew"
package_name = "atuin"
binary_name = "atuin"

[[profiles.packages]]
name = "barb"
manager = "brew"
package_name = "barb"
binary_name = "barb"

[[profiles.packages]]
name = "micro"
description = "more than nano, less then vim"
manager = "brew"
package_name = "micro"
binary_name = "micro"

[[profiles]]
name = "Linux"
description = "my linux machine setup"
synced_files = [
    ".gitconfig",
    ".p10k.zsh",
    ".profile",
    ".sshconfig",
    ".tmux.conf",
    ".vimrc",
    ".zshenv",
    ".zshrc",
]
packages = []

[[profiles]]
name = "Exedev"
description = "exe.dev profile for ubuntu"
synced_files = [
    ".bash_logout",
    ".bashrc",
    ".config/atuin",
    ".gitconfig",
    ".profile",
    ".vimrc",
]

[[profiles.packages]]
name = "Atuin"
description = "Magical Shell History"
manager = "custom"
binary_name = "atuin"
install_command = "curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh"
existence_check = "command -v atuin >/dev/null 2>&1"

[[profiles.packages]]
name = "Eza"
description = "Eza for ls"
manager = "apt"
package_name = "eza"
binary_name = "eza"

[[profiles.packages]]
name = "bat"
manager = "apt"
package_name = "bat"
binary_name = "batcat"

[[profiles.packages]]
name = "HTTPIE"
description = "curl alternative"
manager = "apt"
package_name = "httpie"
binary_name = "httpie"

[[profiles.packages]]
name = "Docker Compose"
description = "Docker Compose"
manager = "apt"
package_name = "docker-compose"
binary_name = "docker-compose"
